version: "3.8"

services:
  minio:
    image: minio/minio:latest # תג כללי נתמך
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" #  API  (s3a://)
      - "9001:9001" #  Web Console
    volumes:
      - ./data/minio:/data
    networks:
      - bigdata-net

  spark-master:
    image: bitnami/spark:3.3
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    ports:
      - "7077:7077" #  RPC
      - "8080:8080" #  Master UI  → http://localhost:8080
    networks:
      - bigdata-net

  spark-worker:
    image: bitnami/spark:3.3
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - bigdata-net

networks:
  bigdata-net:
    external: true # נוצר פעם אחת מחוץ לקובץ
