version: "3.8"

services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports: ["9000:9000", "9001:9001"]
    volumes:
      - ./data/minio:/data
    networks: [bigdata-net]

  spark-master:
    build: . # ← יבנה את Dockerfile
    image: spark-custom:3.3 # תג מקומי
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    ports: ["7077:7077", "8080:8080"]
    volumes:
      - ./processing/jobs:/opt/bitnami/spark/jobs
    networks: [bigdata-net]

  spark-worker:
    image: spark-custom:3.3
    build: . # ← חשוב! גם כאן build כדי להיות בטוחים
    depends_on: [spark-master]
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    volumes:
      - ./processing/jobs:/opt/bitnami/spark/jobs
    networks: [bigdata-net]

networks:
  bigdata-net:
    external: true
